### ISSUE TITLE
Unplayable file after converting WEM to OGG

### ISSUE THREAD

**Issue by hadoooooouken** [WolvenKit/wwise-audio-tools#14]
File was extracted with WolvenKit 8.7.0 from Cyberpunk 2077 v.1.61
`wwtools wem judy_q004_f_15a8a4c8885ae014.wem`
gave me **judy_q004_f_15a8a4c8885ae014.ogg** - but I can't play this file with any app.
(attached both files)
```
F:\ww_test>ffplay judy_q004_f_15a8a4c8885ae014.ogg
ffplay version N-109078-g2d25f33a7e-20221113 Copyright (c) 2003-2022 the FFmpeg developers
  built with gcc 12.2.0 (crosstool-NG 1.25.0.90_cf9beb1)
  configuration: --prefix=/ffbuild/prefix --pkg-config-flags=--static --pkg-config=pkg-config --cross-prefix=x86_64-w64-mingw32- --arch=x86_64 --target-os=mingw32 --enable-gpl --enable-version3 --disable-debug --disable-w32threads --enable-pthreads --enable-iconv --enable-libxml2 --enable-zlib --enable-libfreetype --enable-libfribidi --enable-gmp --enable-lzma --enable-fontconfig --enable-libvorbis --enable-opencl --disable-libpulse --enable-libvmaf --disable-libxcb --disable-xlib --enable-amf --enable-libaom --enable-libaribb24 --enable-avisynth --enable-chromaprint --enable-libdav1d --enable-libdavs2 --disable-libfdk-aac --enable-ffnvcodec --enable-cuda-llvm --enable-frei0r --enable-libgme --enable-libkvazaar --enable-libass --enable-libbluray --enable-libjxl --enable-libmp3lame --enable-libopus --enable-librist --enable-libssh --enable-libtheora --enable-libvpx --enable-libwebp --enable-lv2 --disable-libmfx --enable-libvpl --enable-openal --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopenmpt --enable-librav1e --enable-librubberband --enable-schannel --enable-sdl2 --enable-libsoxr --enable-libsrt --enable-libsvtav1 --enable-libtwolame --enable-libuavs3d --disable-libdrm --disable-vaapi --enable-libvidstab --enable-vulkan --enable-libshaderc --enable-libplacebo --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxvid --enable-libzimg --enable-libzvbi --extra-cflags=-DLIBTWOLAME_STATIC --extra-cxxflags= --extra-ldflags=-pthread --extra-ldexeflags= --extra-libs=-lgomp --extra-version=20221113
  libavutil      57. 42.100 / 57. 42.100
  libavcodec     59. 52.102 / 59. 52.102
  libavformat    59. 34.101 / 59. 34.101
  libavdevice    59.  8.101 / 59.  8.101
  libavfilter     8. 50.100 /  8. 50.100
  libswscale      6.  8.112 /  6.  8.112
  libswresample   4.  9.100 /  4.  9.100
  libpostproc    56.  7.100 / 56.  7.100
[ogg @ 000001c66b5abf00] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 53 times
[ogg @ 000001c66b5abf00] CRC mismatch! vq=    0KB sq=    0B f=0/0
    Last message repeated 4 times
judy_q004_f_15a8a4c8885ae014.ogg: End of file
```
[test.zip](https://github.com/WolvenKit/wwise-audio-tools/files/10003455/test.zip)

**Comment by hadoooooouken** [comment]
The same file was successfully converted with WEM to OGG, WAV to WEM converter from:
https://residentevilmodding.boards.net/thread/12359/wem-ogg-wav-converter-batch

```
WEM RIFF/RIFX to OGG Converter 0.24 by HCS, RE-checked

 .WEM: judy_q004_f_15a8a4c8885ae014.wem
RIFF WAVE 2 channels 48000 Hz 191616 bps
500759 samples
- 2 byte packet headers, no granule
- stripped setup header
- external codebooks (_wem_codebooks_aoTuV_603.bin)
- modified Vorbis packets
  .OGG: judy_q004_f_15a8a4c8885ae014.ogg
Done!

OGG Revorb
Total:
 .OGG [1 files]

 Revorb starting
 Revorb finished

 [EXIT]
(c) CAPCOM CO., LTD. 2019 ALL RIGHTS RESERVED .
```

**Comment by ADawesomeguy** [comment]
Just to clarify -- it doesn't work with `ww2ogg` + `revorb` on their own right?

**Comment by hadoooooouken** [comment]
> 

ww2ogg input.wem -o output.ogg - noise
revorb output.ogg revorbed_output.ogg - still noise and ffplay gives errors (many [ogg @ 000001e00fc0c2c0] invalid pts -57536)

ww2ogg input.wem -o output.ogg --pcb packed_codebooks.bin - noise
revorb output.ogg revorbed_output.ogg - noise+errors

ww2ogg input.wem -o output.ogg --pcb packed_codebooks_aoTuV_603.bin - works
revorb output.ogg revorbed_output.ogg - works (size reduced)

**Comment by ADawesomeguy** [comment]
```
ww2ogg input.wem -o output.ogg --pcb packed_codebooks_aoTuV_603.bin
revorb output.ogg revorbed_output.ogg
```
This should be the equivalent of what `wwtools` does. Let me see what's going wrong.

**Comment by nikich340** [comment]
+, this bug persist for all cp77 VO files.

**Comment by abheekda1** [comment]
@nikich340 are you able to get it working with some combination of `ww2ogg` and `revorb`?

**Comment by nikich340** [comment]
> 

Yes, like said above.

**Comment by abheekda1** [comment]
This is really weird, I think I may add some args to allow different codebooks. Thanks for the info.

**Comment by abheekda1** [comment]
@nikich340 could you try it with the different compile definitions and/or upload a sample file that doesn't work?

**Comment by Jan-Ka** [comment]
_Sorry for the almost 1-year issue necro, @abheekda1_

 
 
 
I work on a different project that uses `ww2ogg` and wanted to switch to this tool, but couldn't make it work with the same issue that OP mentioned.

Things I tried, that didn't result in a working file:

- `PACKED_CODEBOOKS_AOTUV=ON`, and also checked that the transformed codebooks are the same as those in `ww2og`
  - I changed https://github.com/WolvenKit/wwise-audio-tools/blob/f550eca33d0be0a855a69163433cf6026a921538/CMakeLists.txt#L45 to load `packed_codebooks.cpp` for testing
- Load `packed_codebooks_aoTuV_603.bin` directly inside `codebook_library::codebook_library`

Things that did work:

- Breaking the codebooks (wrong path / mangled bytes) leads to the same errors in both `wwtools` and `ww2ogg`
- Validated the test file `tests\testdata\wem\test1.wem` in your library works with `ww2ogg` using `packed_codebooks_aoTuV_603`
- Validated my file works with `ww2ogg` using `packed_codebooks_aoTuV_603`

Notes:

- converted files between `ww2ogg` and `wwtools` look very similar in hex (header + footer section matches), so maybe it is missing a checksum or length?
- Not calling `revorb` (e.g. commenting the call out in `wem_to_ogg`) doesn't seem to make things different

I'm not very versed in C/C++ but I think I managed to check all surface-level sources of error. Sorry that I can't be of more help.

Attached are (non-original/non-copyrighted) audio files (`*.wem` and `*.ogg`) that work in CP2077 and `ww2ogg` but not in `wwtools` with `packed_codebooks_aoTuV_603`

[cp2077_test_wem_ogg.zip](https://github.com/WolvenKit/wwise-audio-tools/files/13880946/cp2077_test_wem_ogg.zip)

**Comment by abheekda1** [comment]
There's no such thing as an issue necro, thank you for all the info! I've been busy for about the last year but I'll take a look at this as soon as I can, pretty much perfect timing to resolve it.

**Comment by abheekda1** [comment]
I'm fairly certain it's a line endings issue. Super annoying but a simple fix, I'll push it soon.
![2024-01-09_21-14](https://github.com/WolvenKit/wwise-audio-tools/assets/67982792/b6b8f629-fac9-4e59-a8fe-8315f438fe36)
![2024-01-09_21-14_1](https://github.com/WolvenKit/wwise-audio-tools/assets/67982792/72699c64-5060-452c-a986-c3523cf22a72)
