### ISSUE TITLE
Types need to be fixed for exporting C-style symbols

### ISSUE THREAD

**Issue by ADawesomeguy** [WolvenKit/wwise-audio-tools#3]
E.g. `std::string` needs to be `char*` or `extern "C"` needs to be gotten rid of. I'm not particularly experienced or sure what the right way to go about it is.

**Comment by SpontanCombust** [comment]
Unless you're planning for this repo to be used as a C library then perhaps simply deleting the `extern "C"` sections is a valid option? It wouldn't hurt much, that's for sure.

**Comment by ADawesomeguy** [comment]
Yep that’s what I was thinking. Would you like to do that or should I?
